version: "3.5"

services:
  traefik:
    container_name: traefik image: traefik
    restart: always
    depends_on:
      - metabase
    command:
 #     - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
 #     - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=joseph@my_domain_name.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks: - proxy
      - internal
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    container_name: db-postgres
    image: postgres:11.5
    restart: always  
    volumes:
      - "./data/pgdata:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=MYMETABASESECRET 
    networks:
      - internal

  metabase:
    container_name: metabase-app
    image: metabase/metabase:latest
    restart: always 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.rule=Host(`my_domain_name.com`)"
      - "traefik.http.routers.metabase.entrypoints=websecure"
      - "traefik.http.routers.metabase.tls.certresolver=myhttpchallenge"
    volumes:
      - "./data/metabase-data:/metabase-data"
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=MYMETABASESECRET
      - MB_DB_HOST=db
    networks:
      - internal

networks:
    proxy:
      driver: bridge
    internal: 
